# Generated by Django 4.1.5 on 2023-03-16 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_message_conversation_remove_message_read_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='eduacational_qualifications',
            new_name='educational_qualifications',
        ),
    ]
