# Generated by Django 4.1.5 on 2023-03-24 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_eduacational_qualifications_profile_educational_qualifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='profileimg',
            field=models.ImageField(default='blank_profile_pic.png', upload_to=''),
        ),
    ]
