# Generated by Django 4.1.5 on 2023-03-31 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_commentpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentpost',
            name='post_id1',
            field=models.CharField(default=0, max_length=500),
        ),
    ]
